language: dart

dart:
  - 2.1.0
  - dev

script: ./tool/travis.sh

# Only building master means that we don't run two builds for each pull request.
branches:
  only: [master]

cache:
  directories:
  - $HOME/.pub-cache
