name: vector_math
version: 2.1.5-dev
description: A Vector Math library for 2D and 3D applications.
repository: https://github.com/google/vector_math.dart

environment:
  sdk: ^3.0.0

dev_dependencies:
  benchmark_harness: ^2.0.0
  build_runner: ^2.0.0
  build_test: ^2.0.0
  build_web_compilers: ^4.0.0
  dart_flutter_team_lints: ^1.0.0
  path: ^1.8.0
  test: ^1.16.0
