name: vector_math
version: 2.0.0-dev
author: John McCutchan <john@johnmccutchan.com>
description: A Vector Math library for 2D and 3D applications.
homepage: https://github.com/johnmccutchan/vector_math
environment:
  sdk: '>=1.0.0'
dev_dependencies:
  benchmark_harness: any
  browser: any
  path: '>=1.0.0 <2.0.0'
  test: '>=0.12.0-beta.1 <0.13.0'
