name: vector_math
version: 2.1.0-nullsafety
description: A Vector Math library for 2D and 3D applications.
homepage: https://github.com/google/vector_math.dart

environment:
  # This must remain a tight constraint (only allow dev versions) until nnbd is
  # stable.
  sdk: '>=2.9.0-18.0 <2.9.0'

dev_dependencies:
  benchmark_harness: any
  path: ^1.0.0
  pedantic: ^1.0.0
  test: ^1.6.0

  build_runner: ^1.0.0
  build_test: ^0.10.0
  build_web_compilers: '>=1.2.0 <3.0.0'

dependency_overrides:
  async:
    git:
      url: git://github.com/dart-lang/async.git
      ref: null_safety
  boolean_selector:
    git:
      url: git://github.com/dart-lang/boolean_selector.git
      ref: null_safety
  charcode:
    git:
      url: git://github.com/dart-lang/charcode.git
      ref: null_safety
  collection:
    git:
      url: git://github.com/dart-lang/collection.git
      ref: null_safety
  matcher:
    git:
      url: git://github.com/dart-lang/matcher.git
      ref: null_safety
  meta:
    git:
      url: git://github.com/dart-lang/sdk.git
      ref: null_safety-pkgs
      path: pkg/meta
  path:
    git:
      url: git://github.com/dart-lang/path.git
      ref: null_safety
  pedantic:
    git:
      url: git://github.com/dart-lang/pedantic.git
      ref: null_safety
  pool:
    git:
      url: git://github.com/dart-lang/pool.git
      ref: null_safety
  source_span:
    git:
      url: git://github.com/dart-lang/source_span.git
      ref: null_safety
  stack_trace:
    git:
      url: git://github.com/dart-lang/stack_trace.git
      ref: null_safety
  stream_channel:
    git:
      url: git://github.com/dart-lang/stream_channel.git
      ref: null_safety
  string_scanner:
    git:
      url: git://github.com/dart-lang/string_scanner.git
      ref: null_safety
  term_glyph:
    git:
      url: git://github.com/dart-lang/term_glyph.git
      ref: null_safety
  test_api:
    git:
      url: git://github.com/dart-lang/test.git
      ref: null_safety
      path: pkgs/test_api
  test_core:
    git:
      url: git://github.com/dart-lang/test.git
      ref: null_safety
      path: pkgs/test_core
  test:
    git:
      url: git://github.com/dart-lang/test.git
      ref: null_safety
      path: pkgs/test
