name: vector_math
version: 1.4.5-dev
author: John McCutchan <john@johnmccutchan.com>
description: A Vector Math library for 2D and 3D applications.
homepage: https://github.com/johnmccutchan/vector_math
environment:
  sdk: '>=1.0.0'
dev_dependencies:
  benchmark_harness: '>=1.0.4 <2.0.0'
  browser: '>=0.10.0+2 <0.11.0'
  hop: '>=0.30.3 <0.31.0'
  unittest: '>=0.11.0+5 <0.12.0'
