name: vector_math
version: 2.0.0-dev
author: John McCutchan <john@johnmccutchan.com>
description: A Vector Math library for 2D and 3D applications.
homepage: https://github.com/johnmccutchan/vector_math
environment:
  sdk: '>=1.0.0'
dev_dependencies:
  benchmark_harness: any
  browser: any
  hop: '>=0.30.3 <0.32.0'
  test: '>=0.12.0-beta.1 <0.13.0'
